name: push test
on:
  push:
    branches:
    - "*"
jobs:
  push-ping:
    runs-on: ubuntu-20.04
    steps:
    - name: push-ping
      run: echo "event name" - ${{ github.event_name }} "\nevent action" - ${{ github.event.action }}
