name: push test
on:
  push:
    branches:
    - "*"
jobs:
  push-ping:
    runs-on: ubuntu-20.04
    steps:
    - name: push-ping
      run: echo "event namr" ${{ github.event_name }}
      run: echo "event action" ${{ github.event.action }}