name: push test
on:
  # pull_request_target:
  #   types: [opened, reopened, synchronize, edited]
  #   branches:
  #   - "*"
  push:
    branches-ignore:
    - "release-*""
jobs:
  push-ping:
    runs-on: ubuntu-20.04
    steps:
    - name: PR
      run: |
        echo "Opened PR or push"
        echo "ref name -" ${{ github.ref_name }} 
        echo "event name -" ${{ github.event_name }} 
        echo "event action -" ${{ github.event.action }}
