name: build release
on:
  pull_request_target:
    branches:
    - "release-*"
    types:
    - closed
jobs:
  build_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
    - name: echo
      run: |
        echo "Build release"
        echo "ref name -" ${{ github.ref_name }} 
        echo "event name -" ${{ github.event_name }} 
        echo "event action -" ${{ github.event.action }}